window.JN_DATA = {
  name: 'James A. Nguyen',
  tagline: 'University of California, Irvine',
  role: 'Ph.D, Statistics',
  cohort: 'co. 2032',
  location: 'Irvine, California',
  about: `Hello — I'm James A. Nguyen, a recent graduate from the University of California, Irvine (UCI) with a B.S. in Applied Mathematics. I'm pursuing a Ph.D. in Statistics under the advisement of Dr. Sudderth and Dr. Mandt, with whom I am focused on problems related to the computational limitations of Bayesian inference. I'm especially interested in developing efficient inference methods for variational approaches applied to high-dimensional data, with applications in machine learning.`,
  projects: [
    {
      id: 'spectral_sampling',
      num: '01',
      year: '2025',
      tag: 'NUMERICAL LINEAR ALGEBRA',
      title: 'Spectrally-Assisted Sampling for Randomized Kaczmarz',
      shortTitle: 'Spectrally-Assisted Sampling',
      desc: 'Aiming to address inefficiencies in the standard random sampling distribution for Randomized Kaczmarz and related algorithms, we explore alternatives that promote faster, more reliable convergence on ill-conditioned, overdetermined systems of linear inequalities.',
      kind: 'iterative solvers',
      page: 'projects/spectral_sampling.html',
      arxiv: 'https://arxiv.org/abs/2407.00000',
      pdf: 'files/read_between_the_hyperplanes.pdf',
      collaborators: ['Dr. E. Sudderth', 'Dr. S. Mandt'],
      status: 'preprint · under review',
      keywords: ['Randomized Kaczmarz', 'spectral sampling', 'ill-conditioned systems', 'convergence rates'],
    },
    {
      id: 'hiv_tb',
      num: '02',
      year: '2024',
      tag: 'EPIDEMIOLOGY · PUBLIC HEALTH',
      title: 'HIV on Tuberculosis Treatment Outcomes in Botswana',
      shortTitle: 'HIV on TB Treatment Outcomes',
      desc: 'An epidemiological study on the impact of public health policy in Gaborone, Botswana in response to the high prevalence of HIV and its effect on tuberculosis treatment outcomes — adjusted for universal access to antiretroviral therapy.',
      kind: 'causal inference',
      page: 'projects/hiv_tb.html',
      arxiv: null,
      pdf: 'files/hiv_tb.pdf',
      collaborators: ['Botswana Ministry of Health (data)', 'Dr. M. Mbulaiteye'],
      status: 'report · 2024',
      keywords: ['causal inference', 'public health', 'ART', 'Botswana'],
    },
    {
      id: 'hippocampal_replay',
      num: '03',
      year: '2023',
      tag: 'COMPUTATIONAL NEUROSCIENCE',
      title: 'Hippocampal Replay of Nonspatial Sequences',
      shortTitle: 'Hippocampal Replay',
      desc: 'An exploratory analysis on the neuronal decoding of odor presentations in the hippocampus — a look into the brain and how understanding it could inform the treatment and identification of cognitive diseases related to working memory.',
      kind: 'neural decoding',
      page: 'projects/hippocampal_replay.html',
      arxiv: null,
      pdf: 'files/hippocampal_ensembles.pdf',
      collaborators: ['Dr. N. Fortin lab, UCI CNLM'],
      status: 'published · Nature Communications',
      publication: 'files/nature_communications.pdf',
      keywords: ['hippocampus', 'replay', 'neural decoding', 'working memory'],
    },
  ],
  nav: [
    { label: 'About', href: '#about' },
    { label: 'Projects', href: '#projects' },
    { label: 'Instruction', href: 'instruction.html' },
    { label: 'Contact', href: '#contact' },
  ],
  hamburger: [
    { label: 'CV', href: 'cv.html', file: 'files/nguyenJames_cv.pdf' },
    { label: 'Collaborators', href: 'collaborators.html' },
    { label: "A Student's Guide to Numerical Bayes", href: "A Student's Guide to Numerical Bayes.html" },
  ],
  collaborators: [
    { name: 'Dr. Erik Sudderth', role: 'Advisor — Bayesian ML', inst: 'UC Irvine, Computer Science' },
    { name: 'Dr. Stephan Mandt', role: 'Co-Advisor — Variational Inference', inst: 'UC Irvine, Computer Science' },
    { name: 'Dr. Norbert Fortin', role: 'Hippocampal replay', inst: 'UC Irvine, CNLM' },
    { name: 'Dr. Babak Shahbaba', role: 'Statistical neuroscience', inst: 'UC Irvine, Statistics' },
  ],
  cv: {
    education: [
      { year: '2026 –', title: 'Ph.D, Statistics', inst: 'University of California, Irvine', note: 'Advisors: Dr. Sudderth · Dr. Mandt' },
      { year: '2022 – 2025', title: 'B.S., Applied Mathematics', inst: 'University of California, Irvine', note: 'Emphasis in probability & computation · magna cum laude' },
    ],
    research: [
      { year: '2025 –', title: 'Graduate Researcher', inst: 'Sudderth & Mandt Labs, UCI', note: 'Variational Bayesian inference for high-dim data' },
      { year: '2023 – 2025', title: 'Undergraduate Researcher', inst: 'Fortin Lab, UCI CNLM', note: 'Hippocampal replay · nonspatial sequence decoding' },
    ],
    awards: [
      { year: '2025', title: 'Chancellor\u2019s Award for Excellence in Undergraduate Research' },
      { year: '2024', title: 'UCI Statistics Honors Program' },
      { year: '2023', title: 'NSF Research Experience for Undergraduates (REU)' },
    ],
    teaching: [
      { year: '2025', title: 'STATS 120A · Intro to Probability (TA)' },
      { year: '2024', title: 'MATH 3A · Linear Algebra (Reader)' },
    ],
  },
  contacts: [
    { label: 'email', value: 'nguyen.james115@gmail.com', href: 'mailto:nguyen.james115@gmail.com' },
    { label: 'linkedin', value: 'in/jamesanguyen115', href: 'https://www.linkedin.com/in/jamesanguyen115' },
    { label: 'github', value: 'janguyen115', href: 'https://github.com/janguyen115' },
    { label: 'scholar', value: 'Google Scholar', href: 'https://scholar.google.com/citations?user=Hm5224EAAAAJ&hl=en' },
    { label: 'arxiv', value: 'arxiv.org/a/nguyen_j', href: 'https://arxiv.org/search/math?searchtype=author&query=Nguyen,+J' },
    { label: 'instagram', value: '@jamesanguyen', href: 'https://www.instagram.com/jamesanguyen/' },
  ],
};
